version: 1

jobs:
  test:
    image: thrive/devcenter-ci:v1
    cache:
      loadFrom:
        - v1-{Branch}-build
      writeTo: v1-{Branch}-build
      system:
        /root/.nuget: v1-nuget
    steps:
      - run:
           command: dotnet restore
      - run:
          name: Dotnet tools
          command: ./ef.rb -i
      - run:
          name: Build
          command: dotnet build /warnaserror
      - run:
          name: Setup test "secrets"
          command: cd Server.Tests && dotnet user-secrets set UnitTestConnection 'User ID=devcenter;Password=testing;Server=localhost;Port=5432;Database=thrivedevcenter_unittest;Integrated Security=true;Pooling=true;' && cd ../AutomatedUITests && dotnet user-secrets set IntegrationTestConnection 'User ID=devcenter;Password=testing;Server=localhost;Port=5432;Database=thrivedevcenter_test;Integrated Security=true;Pooling=true;'
      - run:
          name: Test
          command: dotnet test
