version: 1

jobs:
  test:
    image: thrive/devcenter-ci:v3
    cache:
      loadFrom:
        - v1-{Branch}-build
      writeTo: v1-{Branch}-build
      system:
        /root/.nuget: v1-nuget
        /root/.cache/ms-playwright: v1-playwright
    steps:
      - run:
           command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Setup UI test browsers
          command: pwsh AutomatedUITests/bin/Debug/net6.0/playwright.ps1 install
      - run:
          name: Setup test "secrets"
          command: cd Server.Tests && dotnet user-secrets set UnitTestConnection 'User ID=devcenter;Password=testing;Server=localhost;Port=5432;Database=thrivedevcenter_unittest;Integrated Security=true;Pooling=true;' && cd ../AutomatedUITests && dotnet user-secrets set IntegrationTestConnection 'User ID=devcenter;Password=testing;Server=localhost;Port=5432;Database=thrivedevcenter_test;Integrated Security=true;Pooling=true;'
      - run:
          name: Test
          command: dotnet test
  lint:
    image: thrive/devcenter-ci:v3
    cache:
      loadFrom:
        - v1-{Branch}-build
      writeTo: v1-{Branch}-build
      system:
        /root/.nuget: v1-nuget
    steps:
      - run:
          name: Build list of changed files
          # Remove the cat here once artifact uploads is done:
          command: |
            git diff-tree --no-commit-id --name-only -r HEAD..origin/$CI_DEFAULT_BRANCH > files_to_check.txt
            git diff-tree --no-commit-id --name-only -r HEAD..$CI_EARLIER_COMMIT >> files_to_check.txt || echo compare with previous commit failed
            echo Changed files:
            cat files_to_check.txt
      - run:
          command: dotnet restore
      - run:
          name: Build with warnings
          command: ruby check_formatting.rb -c compile
      - run:
          name: Jetbrains inspectcode
          command: ruby check_formatting.rb -c inspectcode
